### ISSUE TITLE
Does not work on IntelliJ IDEA 2020.2.3 (Ultimate Edition)

### ISSUE THREAD

**Issue by yarco** [fehnomenal/intellij-direnv#3] opened 2020-11-18 01:21 UTC
Details:
Build #IU-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Trying to run a Java (Gradle) application using Run.. -> Application 
env vars do not show up when running as well as when debugging.
Pressed the button a million times to no avail.

Would be happy to provide more info if needed. Please let me know. 

Thanks for creating such a cool plugin!!!

**Comment by yarco** [comment] 2020-11-18 01:32
Created a maven project, included a sample `.envrc`file in it, clicked the button, went to Run.. -> Application .. ; Env vars were not there as well

**Comment by fehnomenal** [comment] 2020-11-19 08:21
I just did the same (maven and gradle probably also others) and could reproduce the issue.

As a workaround I `direnv allow`ed in the terminal and reopened the project then it worked.

I will add some debug output to the plugin.

**Comment by yarco** [comment] 2020-11-19 15:26
Do you mean in the terminal inside of intellij? I ran the allow command inside the of that terminal as well as inside of an external terminal, and still could not get it to work. Would be glad to provide any /all debug logs. Please let me know! ;)

**Comment by fehnomenal** [comment] 2020-11-23 12:51
I think it does not matter which terminal you execute direnv in as long as it does not give any error.

I am currently experiencing the same with Android Studio 4.2 Canary 16. Strange enough the plugin does work while debugging but not when running the IDE standalone...

Could you please
1. Enable debug logging by <kbd>Help</kbd> > <kbd>Diagnostic Tools</kbd> > <kbd>Debug Log Settings...</kbd> and entering `#systems.fehn.intellijdirenv:trace`.
2. Install the debug version (https://github.com/fehnomenal/intellij-direnv/releases/tag/untagged-d006dd77c1b52f79675a) manually (see readme for instructions).
3. Try to import from direnv (either by the action or the new popup on project load).
4. Post a link to your `idea.log` (<kbd>Help</kbd> > <kbd>Show Log in ...</kbd>).

Thank you!

**Comment by yarco** [comment] 2020-11-24 06:15
I cannot see new releases with the link provided in 2. I tried compiling it from master, but since I have OSX Big Sur, there's a problem ...  
<img width="996" alt="Screen Shot 2020-11-23 at 10 13 01 PM" src="https://user-images.githubusercontent.com/271510/100055763-39742c00-2dd9-11eb-9e83-915461bfae7d.png">
<img width="1307" alt="Screen Shot 2020-11-23 at 10 13 06 PM" src="https://user-images.githubusercontent.com/271510/100055764-39742c00-2dd9-11eb-9543-a8a71a5fa48c.png">

**Comment by fehnomenal** [comment] 2020-11-24 07:50
Wow, it seems only I can see draft releases...
Please use this file: [Direnv integration-0.1.0.zip](https://github.com/fehnomenal/intellij-direnv/files/5588199/Direnv.integration-0.1.0.zip)

**Comment by yarco** [comment] 2020-11-24 17:28
[idea.log](https://github.com/fehnomenal/intellij-direnv/files/5591624/idea.log)
It is a clean log - I used a dummy project with the most basic functionality

**Comment by fehnomenal** [comment] 2020-11-24 22:59
2020-11-24 09:23:26,191 [   7093]  DEBUG - jdirenv.services.DirenvService - Did not find direnv executable in path 

How do you call direnv in a terminal? This is probably a OSX thing...

**Comment by yarco** [comment] 2020-11-24 23:38
I get this `/usr/local/bin/direnv` if I run from a standard OSX terminal + iterm (the one I use) + Intellij "inner" terminal - I get this

**Comment by fehnomenal** [comment] 2020-11-25 00:05
I am searching the absolute path here 
https://github.com/fehnomenal/intellij-direnv/blob/0ca8ba8002389c9091f10c3291cc649a4fd2bab3/src/main/kotlin/systems/fehn/intellijdirenv/services/DirenvService.kt#L15-L19

Could you please post your `$PATH` if it does not contain sensitive values?

Please test also this version which skips all tests whether direnv is available and just calls `direnv` (not the absolute path): [Direnv integration-0.1.0.zip](https://github.com/fehnomenal/intellij-direnv/files/5593467/Direnv.integration-0.1.0.zip)

**Comment by yarco** [comment] 2020-11-25 00:21
So this is what I got from the logs:
`java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.io.IOException: Cannot run program "direnv" (in directory "/Users/yarco/tmp2"): error=2, No such file or directory
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.security.PrivilegedActionException: java.io.IOException: Cannot run program "direnv" (in directory "/Users/yarco/tmp2"): error=2, No such file or directory
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	... 17 more
Caused by: java.io.IOException: Cannot run program "direnv" (in directory "/Users/yarco/tmp2"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at systems.fehn.intellijdirenv.services.DirenvProjectService.executeDirenv(DirenvProjectService.kt:142)
	at systems.fehn.intellijdirenv.services.DirenvProjectService.importDirenv(DirenvProjectService.kt:42)
	at systems.fehn.intellijdirenv.listeners.MyProjectManagerListener$projectOpened$notification$1.accept(MyProjectManagerListener.kt:33)
	at systems.fehn.intellijdirenv.listeners.MyProjectManagerListener$projectOpened$notification$1.accept(MyProjectManagerListener.kt:14)
	at com.intellij.notification.NotificationAction$Simple.actionPerformed(NotificationAction.java:82)
	at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:31)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
	at com.intellij.notification.Notification.fire(Notification.java:258)
	at com.intellij.notification.impl.NotificationsManagerImpl$14.linkSelected(NotificationsManagerImpl.java:780)
	at com.intellij.notification.impl.NotificationsManagerImpl$14.linkSelected(NotificationsManagerImpl.java:775)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:138)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:348)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:322)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	... 22 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 53 more`
And my `$PATH`
`/usr/local/opt/openjdk/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/python@3.9/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/Users/yarco/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/usr/local/sbin:/Users/yarco/.local/bin`

**Comment by fehnomenal** [comment] 2020-11-25 06:30
OK, will have to spin up my MacBook to test this further.

**Comment by fehnomenal** [comment] 2020-11-30 09:15
I didn't manage to set up my MacBook but could you please test this version: [Direnv integration-0.1.0.zip](https://github.com/fehnomenal/intellij-direnv/files/5614923/Direnv.integration-0.1.0.zip)

This is probably due to a mismatch of environment variables between the shell and GUI programs on Mac.

**Comment by yarco** [comment] 2020-12-01 06:48
Yup, I think you are right ... 
I get a million of these in the logs now.
[idea.log](https://github.com/fehnomenal/intellij-direnv/files/5620701/idea.log)

`2020-11-30 22:42:04,653 [  38298]  TRACE - jdirenv.services.DirenvService - Did not find direnv executable in path `

I can still access `direnv` in (as installed by `homebrew`)
`/usr/local/bin/direnv`

Perhaps try to hardcode this path in case you cannot find `direnv` in `$PATH`, and check if this file exists, as a quick osx workaround ...

**Comment by fehnomenal** [comment] 2020-12-01 11:33
So, this is something like your personal build. It does not check whether direnv is available but calls `direnv` (like you would in the shell) and falls back to `/usr/local/bin/direnv` if an error occurred.

Please, report back and post the log again.

[Direnv integration-0.1.0.zip](https://github.com/fehnomenal/intellij-direnv/files/5622246/Direnv.integration-0.1.0.zip)

**Comment by yarco** [comment] 2020-12-01 18:28
[idea.log](https://github.com/fehnomenal/intellij-direnv/files/5624631/idea.log)

So seems like direnv works now, however ... my custom env var is still not showing up.

I have this in my `.envrc` file and I run this java code to print out the env vars
`
Map<String, String> env = System.getenv();
        for (String envName : env.keySet()) {
            System.out.format("%s=%s%n", envName, env.get(envName));
        }
`
`export AAAA="aa"`

**Comment by fehnomenal** [comment] 2020-12-02 12:08
In the logs I see multiple of these lines:

    TRACE - .services.DirenvProjectService - Set variable AAAA to "aa"

So the plugin does work now. Thank you very much for this debugging odyssey.

I will soon release an update that should solve this issue for everyone.

---

Probably you are hit by the same problem as me. The JetBrains guys wrote:

```java
  /**
   * <p>A wrapper layer around {@link System#getenv()}.</p>
   *
   * <p>On Windows, the returned map is case-insensitive (i.e. {@code map.get("Path") == map.get("PATH")} holds).</p>
   *
   * <p>On macOS, things are complicated.<br/>
   * An app launched by a GUI launcher (Finder, Dock, Spotlight etc.) receives a pretty empty and useless environment,
   * since standard Unix ways of setting variables via e.g. ~/.profile do not work. What's more important, there are no
   * sane alternatives. This causes a lot of user complaints about tools working in a terminal not working when launched
   * from the IDE. To ease their pain, the IDE loads a shell environment (see {@link #getShellEnv()} for gory details)
   * and returns it as the result.<br/>
   * And one more thing (c): locale variables on macOS are usually set by a terminal app - meaning they are missing
   * even from a shell environment above. This again causes user complaints about tools being unable to output anything
   * outside ASCII range when launched from the IDE. Resolved by adding LC_CTYPE variable to the map if it doesn't contain
   * explicitly set locale variables (LANG/LC_ALL/LC_CTYPE). See {@link #setCharsetVar(Map)} for details.</p>
   *
   * @return unmodifiable map of the process environment.
   */
```
> Source: https://github.com/JetBrains/intellij-community/blob/6e7398e3d37a88c8c2efec3e2466e85f8fc6576b/platform/util/src/com/intellij/util/EnvironmentUtil.java#L67-L84

See also e.g. this issue: https://github.com/flutter/flutter-intellij/issues/601#issuecomment-276559068

I guess when you run your code from the shell it should work (but of course, this plugin won't run then. So this can only work if you configured your shell to import from the `.envrc` file).

I'm closing this issue as the second problem is not related to this plugin.

**Closed by fehnomenal** 2020-12-02 12:08 UTC
Labels: bug

**Comment by yarco** [comment] 2020-12-03 19:58
Glad I could help! 
So essentially, I cannot get my simple app, as executed from Run/Run.., to run with env vars from my `.envrc` using your plugin? This was my main intention.

**Comment by fehnomenal** [comment] 2020-12-04 09:09
Honestly, I think it depends on which environment IntelliJ is passing to gradle/the `java` call.

You could compare the output of your app with the environment inside your shell (`env` probably works on OSX too) to see if they pass their "extended" environment (like I wrote above).

**Comment by davinkevin** [comment] 2023-06-03 15:58
I have the same problem as @yarco, and on MacOS, it means this plugin is sadly not compatible at all? 

Potentially an issue could be opened to Jetbrains to potentially find a solution, no?

**Comment by rykktiadloans** [comment] 2025-02-24 18:33
Had the same issue, but I think I managed to consistently make work by restarting IntelliJ with `File > Invalidate Caches... > Just restart` (should be in the bottom left). After that it starts working properly
